# Change these first
owner: Cliffe-Group # Your GitHub organization or username, where this repository lives
repo: datalab-status # The name of this repository
assignees: # Users to assign downtime issues (optional)
  - ml-evs

workflowSchedule:
  uptime: "*/30 * * * *"

sites:
  - name: Cliffe Group Datalab
    url: https://datalab.fihm.co.uk
    slug: cliffe-group-datalab
  - name: Cliffe Group Datalab (API)
    url: https://datalab-api.fihm.co.uk/healthcheck/is_ready
    slug: cliffe-group-datalab-api

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /datalab-status
  logoUrl: https://mjcliffe.github.io/CliffeGroupWebsite/images/CliffeGroupLogo.png
  name: Cliffe Group Datalab Status
  # introTitle: 
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Cliffe-Group
    - title: FIHM
      href: https://fihm.co.uk

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
